export const hostApi = 'http://192.168.99.100:8001';

export const config = {
  api: {
    authenticate: hostApi + '/api/token-auth/',
    me: hostApi + '/api/me/',
    member_dashboard: hostApi + '/api/member/',
    member: {
      list: hostApi + '/api/member/members/',
      quick_list: hostApi + '/api/member/members/quick-list/',
      detail: hostApi + '/api/member/members/%s/',
      history: hostApi + '/api/member/members/%s/history/',
      salesperson: hostApi + '/api/member/members/%s/salesperson/',
      organizations: hostApi + '/api/member/members/%s/organizations/',
    },
    salesperson: {
      list: hostApi + '/api/member/salesperson/',
    },
    salesperson_period: {
      list: hostApi + '/api/member/salesperson-period/',
      detail: hostApi + '/api/member/salesperson-period/%s/',
    },
    organization_period: {
      list: hostApi + '/api/member/organization-period/',
      detail: hostApi + '/api/member/organization-period/%s/',
    },
    organization: {
      list: hostApi + '/api/member/organizations',
      quick_list: hostApi + '/api/member/organizations/quick-list/',
      detail: hostApi + '/api/member/organizations/%s/',
      members: hostApi + '/api/member/organizations/%s/members/',
      positions: hostApi + '/api/member/organizations/%s/positions/',
    },
    position_ship: {
      list: hostApi + '/api/member/position-ship/',
      detail: hostApi + '/api/member/position-ship/%s/',
    },
    partner_list: hostApi + '/api/partner/',
    partner_detail: hostApi + '/api/partner/%s/',
    partner_view_list: hostApi + '/api/partner-list/',
    partner_employee_list: hostApi + '/api/partner-employee/',
    partner_employee_detail: hostApi + '/api/partner-employee/%s/',
    partner_employee_choice: hostApi + '/api/partner/%s/employee/',
    partner_member_list: hostApi + '/api/partner/%s/members/',
    partner_member_contract_list: hostApi + '/api/partner-contracts/?member=%s',
    partner_member_contract_detail: hostApi + '/api/partner-contracts/%s/',
    partner_lump_contract_list: hostApi + '/api/partner/%s/lump-contract/',
    partner_lump_contract_detail: hostApi + '/api/partner-lump-contract/%s/',
    partner_lump_order_html: hostApi + '/api/partner/lump/order/%s/',
    partner_lump_order_create: hostApi + '/api/partner/%s/lump-contract/%s/orders/create/',
    partner_pay_notify_recipient_list: hostApi + '/api/partner-pay-notify-recipient/',
    partner_pay_notify_recipient_detial: hostApi + '/api/partner-pay-notify-recipient/%s/',
    partner_bank_account_list: hostApi + '/api/partner-bank-account/',
    partner_bank_account_detail: hostApi + '/api/partner-bank-account/%s/',
    partner_monthly_status: hostApi + '/api/partner/%s/monthly-status/',
    partner_members_order_status: hostApi + '/api/partner/%s/members-order-status/',
    partner_member_orders: hostApi + '/api/partner/%s/members/%s/orders/',
    partner_member_order_detail: hostApi + '/api/partner-member-order/%s/',
    partner_member_order_html: hostApi + '/api/partner/member/order/%s/',
    partner_member_order_create: hostApi + '/api/partner/%s/members/%s/orders/create/',
    partner_divisions_by_month: hostApi + '/api/partner/%s/division/%s/%s/',
    partner_divisions_all_by_month: hostApi + '/api/partner/%s/division/%s/%s/all/',
    partner_divisions_detail_by_month: hostApi + '/api/partner/%s/division/%s/%s/%s/details/',
    customer_list: hostApi + '/api/customer/',
    customer_detail: hostApi + '/api/customer/%s/',
    project_list: hostApi + '/api/vproject/',
    project_detail: hostApi + '/api/project/%s/',
    project_member_list: hostApi + '/api/project_member/',
    project_member_edit: hostApi + '/api/project_member/%s/',
    project_member_delete: hostApi + '/api/project_member/%s/',
    project_attendance_list: hostApi + '/api/project/%s/attendance',
    project_attendance: hostApi + '/api/project/%s/attendance/%s/%s',
    project_attendance_add: hostApi + '/api/member-attendance/',
    project_attendance_detial: hostApi + '/api/member-attendance/%s/',
    project_stage_list: hostApi + '/api/project-stage/',
    project_order_list: hostApi + '/api/project/%s/order',
    project_order_add: hostApi + '/api/customer-order/',
    project_order_detail: hostApi + '/api/customer-order/%s/',
    project_request_html: hostApi + '/api/project/request/%s',
    project_request_create: hostApi + '/api/project/%s/order/%s/request/create/%s/%s',
    turnover_monthly_list: hostApi + '/api/turnover/monthly',
    turnover_monthly_chart: hostApi + '/api/turnover/monthly/chart',
    turnover_yearly_chart: hostApi + '/api/turnover/yearly/chart',
    turnover_division_monthly_chart: hostApi + '/api/turnover/division/monthly/chart',
    turnover_customers_by_month: hostApi + '/api/turnover/customers_by_month/',
    turnover_customers_by_month_detail: hostApi + '/api/turnover/customers_by_month/%s/',
    turnover_customer_by_month: hostApi + '/api/turnover/project/',
    turnover_customer_by_month_detail: hostApi + '/api/turnover/project/%s/',
    turnover_project_by_month: hostApi + '/api/turnover/member/',
    mst_bank_list: hostApi + '/api/bank/',
    mst_bank_account_list: hostApi + '/api/bank-account/',
    attachment_download: hostApi + '/api/attachment/download/%s',
    mail_send: hostApi + '/api/mail/send/',
    mail_partner_order_preview: hostApi + '/api/partner-member-order/%s/mail/',
    mail_partner_lump_order_preview: hostApi + '/api/partner-lump-order/%s/mail/'
  },
  rowsPerPage: 15,
  toastHideDuration: 6000,
  rowsPerPageOptions: [5, 10, 15, 25, 50],
};
